AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Mappings:
  EnvMap:
    prod:
      CertificateArn: arn:aws:acm:us-east-1:066782833234:certificate/00e57f1e-b8b4-48ec-aceb-c16dfca2d2e2
      HostedZoneName: sacra.co.
      RecordSetName: sr-viewer.sacra.co.
      DomainName: sr-viewer.sacra.co
      BucketName: sr-comment-and-gift-viewer
Resources:
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !FindInMap [EnvMap, prod, HostedZoneName]
      RecordSets:
      - Name: !FindInMap [EnvMap, prod, RecordSetName]
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt CloudFront.DomainName
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      BucketName: !FindInMap [EnvMap, prod, BucketName]
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          Action:
          - s3:GetObject
          Effect: Allow
          Resource:
          - !Join ["", ["arn:aws:s3:::", !Ref S3Bucket, "/*"]]
          Principal: "*"
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !FindInMap [EnvMap, prod, DomainName]
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_All
        DefaultCacheBehavior:
          TargetOriginId: S3-origin
          ViewerProtocolPolicy: redirect-to-https
          MaxTTL: 86400
          MinTTL: 86400
          DefaultTTL: 86400
          AllowedMethods:
          - HEAD
          - GET
          CachedMethods:
          - HEAD
          - GET
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Origins:
        - Id: S3-origin
          DomainName: !Join ["", [!FindInMap [EnvMap, prod, BucketName], ".s3.amazonaws.com"]]
          CustomOriginConfig:
            OriginProtocolPolicy: match-viewer
        Restrictions:
          GeoRestriction:
            RestrictionType: none
            Locations: []
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1
          AcmCertificateArn: !FindInMap [EnvMap, prod, CertificateArn]
