AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Mappings:
  EnvMap:
    prod:
      HostedZoneName: sacra.co.
      RecordSetName: sr-viewer.sacra.co.
      BucketName: sr-viewer.sacra.co
Resources:
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !FindInMap [EnvMap, prod, HostedZoneName]
      RecordSets:
      - Name: !FindInMap [EnvMap, prod, RecordSetName]
        Type: A
        AliasTarget:
          HostedZoneId: Z2M4EHUR26P7ZW
          DNSName: s3-website-ap-northeast-1.amazonaws.com
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      BucketName: !FindInMap [EnvMap, prod, BucketName]
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          Action:
          - s3:GetObject
          Effect: Allow
          Resource:
          - !Join ["", ["arn:aws:s3:::", !Ref S3Bucket, "/*"]]
          Principal: "*"
